# Generated by Django 4.2.7 on 2025-12-26 15:20

import animals.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_id', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{15}$', 'Chip ID must be exactly 15 digits')])),
                ('species', models.CharField(choices=[('dog', 'Σκύλος'), ('cat', 'Γάτα'), ('other', 'Άλλο')], max_length=10, verbose_name='Είδος')),
                ('gender', models.CharField(choices=[('male', 'Αρσενικό'), ('female', 'Θηλυκό')], max_length=10, verbose_name='Φύλο')),
                ('age_numeric', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Ηλικία (αριθμός)')),
                ('age_category', models.CharField(blank=True, choices=[('κουταβι', 'Κουτάβι'), ('υπερηλικο', 'Υπερήλικο')], max_length=15, null=True, verbose_name='Κατηγορία Ηλικίας')),
                ('name', models.CharField(max_length=20, verbose_name='Όνομα')),
                ('shelter', models.CharField(default=animals.models.get_default_shelter_name, max_length=100, verbose_name='Καταφύγιο')),
                ('injured', models.BooleanField(default=False, verbose_name='Τραυματισμένο')),
                ('behavior', models.CharField(choices=[('ΗΡΕΜΟ', 'Ήρεμο'), ('ΦΟΒΙΚΟ', 'Φοβικό'), ('ΑΓΡΙΟ', 'Άγριο'), ('ΕΠΙΚΙΝΔΥΝΟ-ΚΑΡΑΝΤΙΝΑ', 'Επικίνδυνο-Καραντίνα')], max_length=25, verbose_name='Συμπεριφορά')),
                ('sterilization_status', models.CharField(choices=[('yes', 'Ναι'), ('no', 'Όχι'), ('scheduled', 'Προγραμματισμένο'), ('unknown', 'Άγνωστη')], max_length=15, verbose_name='Κατάσταση Στείρωσης')),
                ('cage_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Αριθμός Κλουβιού')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('capture_location', models.CharField(max_length=100, verbose_name='Τοποθεσία Εύρεσης')),
                ('capture_date', models.DateField(verbose_name='Ημερομηνία Εύρεσης')),
                ('finder_contact', models.TextField(blank=True, verbose_name='Στοιχεία του ευρέτη')),
                ('public_visibility', models.BooleanField(default=False, verbose_name='Δημόσια προβολή')),
                ('adoption_status', models.CharField(choices=[('available', 'Διαθέσιμο'), ('pending', 'Εκκρεμεί'), ('adopted', 'Υιοθετήθηκε'), ('not_for_adoption', 'Μη διαθέσιμο για υιοθεσία')], default='available', max_length=20, verbose_name='Κατάσταση Υιοθεσίας')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε στις')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Ζώο',
                'verbose_name_plural': 'Ζώα',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(choices=[('rabies', 'Λύσσα'), ('dhppi', 'DHPPi'), ('dappi', 'DAPPi'), ('parainfluenza', 'Parainfluenza'), ('parvovirus', 'Parvovirus'), ('leptospirosis', 'Λεπτοσπείρωση'), ('other', 'Άλλο')], max_length=50, verbose_name='Εμβόλιο')),
                ('other_vaccine_name', models.CharField(blank=True, max_length=100, verbose_name='Όνομα Εμβολίου (αν επιλέξατε Άλλο)')),
                ('date_administered', models.DateField(verbose_name='Ημερομηνία Χορήγησης')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Επόμενη Δόση')),
                ('administered_by', models.CharField(blank=True, max_length=100, verbose_name='Κτηνίατρος')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Παρτίδας')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Καταχώρησης')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animals.animal', verbose_name='Ζώο')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Καταχωρήθηκε από')),
            ],
            options={
                'verbose_name': 'Εμβολιασμός',
                'verbose_name_plural': 'Εμβολιασμοί',
                'ordering': ['-date_administered'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('pathology', 'Παθήσεις'), ('diagnosis', 'Διαγνώσεις')], max_length=15, verbose_name='Τύπος Αρχείου')),
                ('description', models.TextField(max_length=300, verbose_name='Περιγραφή')),
                ('date_recorded', models.DateField(verbose_name='Ημερομηνία Καταγραφής')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε στις')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='animals.animal', verbose_name='Ζώο')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Ιατρικό Αρχείο',
                'verbose_name_plural': 'Ιατρικά Αρχεία',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animal_photos/', verbose_name='Εικόνα')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Κύρια Φωτογραφία')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Λεζάντα')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ανέβηκε στις')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='animals.animal', verbose_name='Ζώο')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ανέβηκε από')),
            ],
            options={
                'verbose_name': 'Φωτογραφία Ζώου',
                'verbose_name_plural': 'Φωτογραφίες Ζώων',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
    ]
