# Generated by Django 4.2.7 on 2025-09-26 14:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_id', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{15}$', 'Chip ID must be exactly 15 digits')])),
                ('species', models.CharField(choices=[('dog', 'Σκύλος'), ('cat', 'Γάτα'), ('other', 'Άλλο')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Αρσενικό'), ('female', 'Θηλυκό')], max_length=10)),
                ('age_numeric', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('age_category', models.CharField(blank=True, choices=[('κουταβι', 'Κουτάβι'), ('υπερηλικο', 'Υπερήλικο')], max_length=15, null=True)),
                ('name', models.CharField(max_length=20)),
                ('injured', models.BooleanField(default=False, verbose_name='Τραυματισμένο')),
                ('behavior', models.CharField(choices=[('ΗΡΕΜΟ', 'Ήρεμο'), ('ΦΟΒΙΚΟ', 'Φοβικό'), ('ΑΓΡΙΟ', 'Άγριο'), ('ΕΠΙΚΙΝΔΥΝΟ-ΚΑΡΑΝΤΙΝΑ', 'Επικίνδυνο-Καραντίνα')], max_length=25)),
                ('vaccination_status', models.CharField(choices=[('ΕΜΒΟΛΙΟ_1', 'Εμβόλιο 1'), ('ΕΜΒΟΛΙΟ_2', 'Εμβόλιο 2'), ('ΕΜΒΟΛΙΟ_3', 'Εμβόλιο 3'), ('ΕΜΒΟΛΙΟ_4', 'Εμβόλιο 4'), ('ΕΜΒΟΛΙΟ_5', 'Εμβόλιο 5'), ('ΕΜΒΟΛΙΟ_6', 'Εμβόλιο 6')], max_length=15)),
                ('sterilization_status', models.CharField(choices=[('yes', 'Ναι'), ('no', 'Όχι'), ('scheduled', 'Προγραμματισμένο')], max_length=15)),
                ('cage_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('capture_location', models.CharField(max_length=100)),
                ('capture_date', models.DateField()),
                ('finder_contact', models.TextField(blank=True, verbose_name='Στοιχεία του ευρέτη')),
                ('public_visibility', models.BooleanField(default=False, verbose_name='Δημόσια προβολή')),
                ('adoption_status', models.CharField(choices=[('available', 'Διαθέσιμο'), ('pending', 'Εκκρεμεί'), ('adopted', 'Υιοθετήθηκε'), ('not_for_adoption', 'Μη διαθέσιμο για υιοθεσία')], default='available', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('pathology', 'Παθήσεις'), ('diagnosis', 'Διαγνώσεις')], max_length=15)),
                ('description', models.TextField(max_length=300)),
                ('date_recorded', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='animals.animal')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animal_photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='animals.animal')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
    ]
