# Generated by Django 4.2.7 on 2025-12-19 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(choices=[('rabies', 'Λύσσα'), ('distemper', 'Νόσος του Carré'), ('parvovirus', 'Παρβοϊός'), ('hepatitis', 'Ηπατίτιδα'), ('leptospirosis', 'Λεπτοσπείρωση'), ('parainfluenza', 'Παραγρίπη'), ('coronavirus', 'Κορωνοϊός'), ('bordetella', 'Μπορντετέλλα'), ('feline_leukemia', 'Λευχαιμία Γάτας'), ('feline_distemper', 'Πανλευκοπενία'), ('calicivirus', 'Καλισιϊός'), ('rhinotracheitis', 'Ρινοτραχειίτιδα'), ('chlamydia', 'Χλαμύδια'), ('fip', 'Λοιμώδης Περιτονίτιδα'), ('other', 'Άλλο')], max_length=50, verbose_name='Εμβόλιο')),
                ('other_vaccine_name', models.CharField(blank=True, max_length=100, verbose_name='Όνομα Εμβολίου (αν επιλέξατε Άλλο)')),
                ('date_administered', models.DateField(verbose_name='Ημερομηνία Χορήγησης')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Επόμενη Δόση')),
                ('administered_by', models.CharField(blank=True, max_length=100, verbose_name='Κτηνίατρος')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Παρτίδας')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Καταχώρησης')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animals.animal', verbose_name='Ζώο')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Καταχωρήθηκε από')),
            ],
            options={
                'verbose_name': 'Εμβολιασμός',
                'verbose_name_plural': 'Εμβολιασμοί',
                'ordering': ['-date_administered'],
            },
        ),
    ]
